### ISSUE TITLE
[Feature Request] Integrate with IPython-notebook-extensions

### ISSUE THREAD

**Issue by benvarkey** [lambdalisue/jupyter-vim-binding#10]
I was wondering if you could add the VIM bindings as an extension to https://github.com/ipython-contrib/IPython-notebook-extensions

I have a fork of your project at 
https://github.com/benvarkey/jupyter-vim-binding, 
which could be integrated to the aforementioned nbextensions project as 
https://github.com/benvarkey/IPython-notebook-extensions/tree/vim_binding/nbextensions/usability/vim_binding

**Comment by lambdalisue** [comment]
Well... I'm sorry but it's not acceptable.
I would like to be the owner of this while i would like to choice the changes without any permission.

**Comment by lambdalisue** [comment]
But this is MIT, if you desire you can. But I don't really think it's good idea to have same plugin in different repo.

**Comment by benvarkey** [comment]
Yeah, I agree that it isn't a good idea to have the same extension in different repo. Guess I will just use this in my fork. 

But, if you could flatten the directory (i.e, move `vim_binding.js` to the root and remove the `nbextensions` directory), that would be really helpful in keeping up-to-date with your repository. Adding the .yaml would be a bonus, but I guess that wouldn't make much sense with your setup.

**Comment by benvarkey** [comment]
To clarify, with a flat directory structure, I can just add your repo as submodule or subtree without any hassle.

**Comment by lambdalisue** [comment]
That sounds acceptable. Adding yaml is also but what's for?

**Comment by lambdalisue** [comment]
> I guess that wouldn't make much sense with your setup

If that file is for supporting this plugin for some features of IPython-notebook-extensions, write documentation about that make sense to the file :-)

**Comment by lambdalisue** [comment]
Oops. I think I was completely mis-understood you.

I thought you said "Please fork IPython-contrib/IPython-notebook-extensions and add your plugin to the repository" thus I said "No."

I'm ok to have a PR from https://github.com/benvarkey/jupyter-vim-binding, just make sure the URL of README.md is correct and enough documentation about the integration in README.md. Anyway, send me a PR :-)

**Comment by benvarkey** [comment]
Sounds good! Will send a PR ASAP.

BTW, what did you mean by

> just make sure the URL of README.md is correct

**Comment by lambdalisue** [comment]
URL of the following part would be changed

> ```
> from notebook.nbextensions import install_nbextension
> install_nbextension('https://goo.gl/5TK96v', user=True, destination="vim_binding.js")
> # Or if you prefre a full URL
> #install_nbextension('https://rawgithub.com/lambdalisue/jupyter-vim-binding/master/nbextensions/vim_binding.js', user=True)
> ```

And adding a section, say "For user who use [ipython-contrib/IPython-notebook-extension](https://github.com/ipython-contrib/IPython-notebook-extensions)", for explain how to install jupyter-vim-bindings through the IPython-notebook-extensions mech.

**Comment by benvarkey** [comment]
OK

**Comment by benvarkey** [comment]
I have made a pull request. Let me know your thoughts.

**Comment by lambdalisue** [comment]
:-)

**Comment by lambdalisue** [comment]
Closed via #11
