### ISSUE TITLE
Windows installation states that VIM binding extension is "possibly incompatible," cannot use VIM binding

### ISSUE THREAD

**Issue by def-mycroft** [lambdalisue/jupyter-vim-binding#104]
### Summary

Hello, 

Having trouble installing on Windows. Following [these](https://github.com/lambdalisue/jupyter-vim-binding/wiki/Installation) instructions, I installed [IPython-notebook-extensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions#conda) with anaconda, and then ran these commands: 

```
# You may need the following to create the directoy
$ mkdir -p $(jupyter --data-dir)/nbextensions
# Now clone the repository
$ cd $(jupyter --data-dir)/nbextensions
$ git clone https://github.com/lambdalisue/jupyter-vim-binding vim_binding
$ chmod -R go-w vim_binding
$ jupyter nbextension enable vim_binding/vim_binding
```

I used the Windows Ubuntu subsystem to run the chmod command in the last line of the above block. 

After launching Jupyter, I see the Nbextensions tab, where I see an extension titled VIM binding with an exclamation mark next to it. Mouseover text states "possibly incompatible." 

### Environment

- [ ] Operating system : Windows 10 
- [ ] Web browser : Chrome 
- [ ] Version or revision of Jupyter Notebook : 4.3.0 
- [ ] Revision of jupyter-vim-binding : latest in git clone 

### Behavior

After following installation instructions, VIM bindings does not install. 

#### Expected

Expected to have functional vim bindings. 

#### Actual

do not have vim bindings. 

### Step by step procedure

1. Install [IPython-notebook-extensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions#conda) with Anaconda. 
2. Execute these commands, running the last command with Ubuntu windows subsystem: 

```
# You may need the following to create the directoy
$ mkdir -p $(jupyter --data-dir)/nbextensions
# Now clone the repository
$ cd $(jupyter --data-dir)/nbextensions
$ git clone https://github.com/lambdalisue/jupyter-vim-binding vim_binding
$ chmod -R go-w vim_binding
$ jupyter nbextension enable vim_binding/vim_binding
```

3. Launch Anaconda prompt, launch notebook server with command `jupyter notebook`
4. Navigate to Nbextensions tab, and observe that "VIM binding" extension is labeled "possibly incompatible." 

### What you have done to solve the issue

Tried uninstalling Anaconda, reinstalling and running same commands.

**Comment by lambdalisue** [comment]
Prob related https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/942

**Comment by lambdalisue** [comment]
And this. https://github.com/jupyter/notebook/issues/2151

**Comment by lambdalisue** [comment]
Prob. Fixed by https://github.com/lambdalisue/jupyter-vim-binding/commit/76156a53b2bdab30205a08a4a9373f5661d76682

Please close this issue if that commit fix your issue.

**Comment by def-mycroft** [comment]
Seems to work now!! Thanks, I love this extension, seriously improves my workflow and QOL.
