### ISSUE TITLE
js throws exception in Jupyter browser after loaded the vim-binding pulgin

### ISSUE THREAD

**Issue by dahakawang** [lambdalisue/jupyter-vim-binding#105]
### Summary
the plugin failed to load and with exception, and binding not working.
```
Loading extension: vim_binding/vim_binding
shortcuts.js?v=20170625214631:161 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Object.attach (shortcuts.js?v=20170625214631:161)
    at Object.attach (vim_binding.js?v=20170625214631:63)
    at vim_binding.js?v=20170625214631:58
    at <anonymous>
```

### Environment

- [ ] Operating system : Ubuntu 14.04
- [ ] Web browser : Chrome 54.0.2840.100(64-bit) / Firefox 34.0
- [ ] Version or revision of Jupyter Notebook : 4.2.1
- [ ] Revision of jupyter-vim-binding : bf8c5035b546d51f03f7c730f74535013e038ee4
**I ran Jupyter backend and browser on different workstations**

### Behavior
binding not working

#### Expected
binding should work

#### Actual
not working, and can see exception throws in the broswer console

### Step by step procedure
nothing special, installed the plugin, and it's just not working when opened jupyter

### What you have done to solve the issue
Both FF and chrome has the same issue

### Remarks
part of the contexts before it throws:
as you can see, somehow km.config is undefined, so next statement will cause exception throw.
not familiar with the code base, really appreciate if you guys can help to troubleshooting. I can provide any information regarding this for further investigation...

![111](https://user-images.githubusercontent.com/2820550/27523576-97aa3d00-5a60-11e7-9381-29ff1833aba7.png)

**Comment by lambdalisue** [comment]
Thanks for the report. It seems a bug introduced from https://github.com/lambdalisue/jupyter-vim-binding/pull/103 

I'll fix it soon.

**Comment by lambdalisue** [comment]
It should be fixed by https://github.com/lambdalisue/jupyter-vim-binding/commit/119bb4544ae1c8922c417c28774d8a091d45856b

Please feel free to reopen the issue if the problem remains 👍

**Comment by dahakawang** [comment]
it works now, thank you!
