### ISSUE TITLE
Extension does not work on jupyterhub

### ISSUE THREAD

**Issue by atomic** [lambdalisue/jupyter-vim-binding#106]
### Summary
vim_binding does not work on jupyterhub, but other extension does.

### Environment

- [ ] Operating system : (e.g. Ubuntu 14.04.5 LTS (host server) )
- [ ] Web browser : (e.g. Google Chrome)
- [ ] Version or revision of Jupyter Notebook : 4.3.0

### Behavior
I work on my notebook remotely using ssh and jupyterhub. I installed vim_binding extension on $(jupyter --data-dir)/nbextensions and is enabled, but the extension does not work at all in the notebook, even after a restart. Other extension like codefolding was installed the same way and worked well.

**Comment by lambdalisue** [comment]
Which version of jupyterhub? Actually I had been using this plugin with jupyterhub about a half year ago.

**Comment by atomic** [comment]
The Jupyter version is 0.7.2. 
Actually, I tested again through ssh on my Chromebook. And, the vim-binding works on my Chromebook remote Jupyter notebook. Previously, it didn't work on Linux Chromium and old version of chrome on windows (not sure the version, but I'll check later).
So, it might be the chrome browser requirement. It's definitely the client side problem.

edit: Nevermind, it works now. The server has to be restarted.
