### ISSUE TITLE
Browser limitation

### ISSUE THREAD

**Issue by yangle** [lambdalisue/jupyter-vim-binding#108]
Regarding the [technical limitations](https://github.com/lambdalisue/jupyter-vim-binding#limitation) due to hard-coded browser keybindings, perhaps it's worth mentioning the chromium-based [Vivaldi](https://vivaldi.com/) browser as an alternative.

In contrast to Google Chrome / Chromium, (almost) all keyboard shortcuts in Vivaldi can be changed / disabled, including (but not limited to) Ctrl-N, Ctrl-T, Ctrl-J, etc.
Furthermore, Vivaldi allows assigning a keyboard shortcut to temporarily [*turn off **all** other browser keyboard shortcuts*](https://www.ghacks.net/2017/02/07/vivaldi-tip-block-all-keyboard-shortcuts/), making all key mappings available for other uses.

(Not affiliated, just a happy user.)

**Comment by lambdalisue** [comment]
I didn't know that thanks. Would you mind if I ask you to write quick documentation about Vivaldi in README and send me a PR?
