### ISSUE TITLE
select multiple cells

### ISSUE THREAD

**Issue by StephaneKazmierczak** [lambdalisue/jupyter-vim-binding#110]
### Summary
I am trying to copy paste cell from one notebook to another 
doing that one cell at a time is tedious and I was looking for a shortcut to select multiple cells and cop/past them 
people report shift k or shift j should be working
in vim binding they are used as extend selected cells above or bellow, not sure if it is the same as without it
on my notebook they behave like j or k alone.

Is there any other shortcut that would work ? 

### Environment

- [ ] Operating system : (e.g. Debian stretch)
- [ ] Web browser : (e.g. Chrome)
- [ ] Version or revision of Jupyter Notebook : (e.g. 5.0.0 )
- [ ] Revision of jupyter-vim-binding : (e.g. 2.0.6)

**Comment by lambdalisue** [comment]
All default mappings are listed here

https://github.com/lambdalisue/jupyter-vim-binding/blob/master/lib/jupyter/shortcuts.js

**Comment by StephaneKazmierczak** [comment]
Thank you for the link with the shortcut ! 
I am not sure what i did wrong yesterday but now the shift+j or shift+k are working as expected

**Comment by lambdalisue** [comment]
:smile:
