### ISSUE TITLE
Support for notebooks in JupyterLab

### ISSUE THREAD

**Issue by joelostblom** [lambdalisue/jupyter-vim-binding#114]
Hi, I have recently started using the Jupyter Notebook again, and you plugin really is fantastic! Thanks for making it!

I am curious if you have any plans to support this plugin with notebooks in the new JupyterLab. I know it's only in beta release right now, so I am just wondering if you think you will be adding support in the future or if it will be too much work to be worthwhile.

**Comment by stsievert** [comment]
The jupyterlab developers are considering adding vim support: https://github.com/jupyterlab/jupyterlab/issues/1362

**Comment by joelostblom** [comment]
@stsievert Thanks for the heads up!

**Comment by lambdalisue** [comment]
Thanks for comment.

Well, I know JupyterLab and I was really looking forward that project. However, as I mentioned in https://github.com/lambdalisue/jupyter-vim-binding/issues/89, recently I changed job and I no longer use jupyter notebook unfortunately. That's why I'm not really welcome to support the new platform in this plugin by myself.

As I said I'm welcome to add contributors, I don't have any negative image for supporting jupyterlab if someone takes care. Or this is MIT plugin so I'm OK if someone use core parts of this plugin in new plugins or jupyterlab itself as long as they read and follow the license :smile:

**Comment by joelostblom** [comment]
Thanks for replying although you don't work on this anymore! I looked more into jupyter lab, it has some nice features, but nothing that I think is better than vim-bindings =) So I will keep using the standalone notebook with your addon.

**Comment by jmeppley** [comment]
FWIW, I have this extension working in JupyterLab. I'm not sure how stable it will be, but it's working. 

I did something like this:

 * created my own personal conda environemnt with jupyter and the jupyter_nbextensions_configurator package.
 * then I followed the enabled use extensions with
```
jupyter nbextensions_configurator enable --user
```
 * then I installed using the instructions in the Readme:
```
# Create required directory in case (optional)
mkdir -p $(jupyter --data-dir)/nbextensions
# Clone the repository
cd $(jupyter --data-dir)/nbextensions
git clone https://github.com/lambdalisue/jupyter-vim-binding vim_binding
# Activate the extension
jupyter nbextension enable vim_binding/vim_binding
```

This is a little bit of black magic, but it seems to work on two different JupyterHubs I use: one that has the extension manager installed and one that doesn't.

**Comment by stsievert** [comment]
Can you put in a PR so I can evaluate? I don't maintain this repo but am interested. Also, there is another vim extension for jupyterlab: https://github.com/jwkvam/jupyterlab-vim.

**Comment by jmeppley** [comment]
I made no code changes. I had an old install that just worked when our
sysadmin setup jupyterlab.

I hadn't seen jupyterlab-vim. That looks like it has the features I need,
thanks!

**Comment by jmeppley** [comment]
Oh.

I just realized I was confusing JupyterLab and JupyterHub again. I have it
working for jupyter *hub*. Nevermind.
