### ISSUE TITLE
Suppoer custom user mappings or settings

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/jupyter-vim-binding#12]
Like `.vimrc`.

**Comment by neelpatel09** [comment]
This would be really great.

**Comment by lambdalisue** [comment]
Add a document. https://github.com/lambdalisue/jupyter-vim-binding#customize

**Comment by pseth** [comment]
I see that I can add custom commands, but is it possible to load the whole vimrc?

**Comment by lambdalisue** [comment]
No, unfortunatly.
This plugin use CodeMirror's Vim mode which mimic Vim feature and is not Vim itself.
