### ISSUE TITLE
insert to normal mode

### ISSUE THREAD

**Issue by exp2logy** [lambdalisue/jupyter-vim-binding#122]
### Summary

Best way to go from insert to normal mode.

### Environment

- [ ] Operating system : (e.g. Ubuntu Gnome 15.04 64bit)
- [ ] Web browser : (e.g. Firefox 44.0.2)
- [ ] Version or revision of Jupyter Notebook : (e.g. 4.1 or 620fb29)
- [ ] Revision of jupyter-vim-binding : (e.g. 5a057d6)

### Behavior

When I'm in insert mode in a cell, what is the shortest way to go into what in Vi is normal mode? 
I notice that Esc+Enter and Esc i i, works? Is this by design?

#### Expected

This is suboptimal compared to just Esc.
In vi I have jj instead of Esc. Is this customizable in the extension?

**Comment by exp2logy** [comment]
The customization instructions worked and jj now configured!

**Comment by zhiyuanpeng** [comment]
which command do you use to configure the jj? I use this CodeMirror.Vim.map("jj", "<Esc>", "insert"), however, it doesn't make sense.

**Comment by XRLuo** [comment]
> The customization instructions worked and jj now configured!

Can you share the specific procedure with us?
