### ISSUE TITLE
Some basic Jupyter keyboard shortcuts not working in Jupyter mode

### ISSUE THREAD

**Issue by sid-kap** [lambdalisue/jupyter-vim-binding#129]
### Environment

- [ ] Operating system : OS X 10.13.6 (17G65)
- [ ] Web browser : 67.0.3396.99
- [ ] Version or revision of Jupyter Notebook : 5.5.0
- [ ] Revision of jupyter-vim-binding : Not sure how to find this (looks like the git repo in `~/.local/share/jupyter/nbextensions/vim_binding` is at commit c9822c753b6acad8b1084086d218eb4ce69950e9, from October 2017)

### Behavior

After I do `:q` to Jupyter mode, I expect shortcuts like <kbd>b</kbd> and <kbd>a</kbd> to create new cells to still work. However, for some reason they stopped working after installing jupyter-vim-binding.

#### Expected

<kbd>b</kbd> should create a new cell below the current cell
<kbd>a</kbd> should create a new cell above the current cell

#### Actual

<kbd>b</kbd> and <kbd>a</kbd> do nothing

**Comment by lambdalisue** [comment]
Please read an introduction of this plugin. It's not issue while this plugin stands for that.

**Comment by sid-kap** [comment]
That was not very informative.
Are you saying that jupyter-vim-binding should not affect those bindings?

**Comment by lambdalisue** [comment]
I'm saying that your expectation is wrong for this plugin.

The purpose of this plugin is providing a Vim-like environment like the introduction said.

> This extension stands for providing a Vim like environment, so it would drastically overwrite the default mappings and introduce a new behaviors. For example

Additionally, what you want to do is listed in help.

<img width="720" alt="untitled 2018-07-19 02-46-01" src="https://user-images.githubusercontent.com/546312/42898474-42c079d8-8afe-11e8-8000-c8ac3ba98abd.png">
