### ISSUE TITLE
 want to use Vim keybindings whenever I run the JupyterLab text editor. Right now I have to go to Settings -> Text Editor Key Map -> vim every time I start a new run to get the behavior I want. Is there a way to make this a permanent user setting whenever I run JupyterLab? 

### ISSUE THREAD

**Issue by blackazzazzin** [lambdalisue/jupyter-vim-binding#131]
Hi!
I want to use Vim keybindings whenever I run the JupyterLab text editor. Right now I have to go to Settings -> Text Editor Key Map -> vim every time I start a new run to get the behavior I want. Is there a way to make this a permanent user setting whenever I run JupyterLab?

**Comment by lambdalisue** [comment]
I guess you are looking for https://github.com/jwkvam/jupyterlab-vim

**Comment by blackazzazzin** [comment]
Hi, sorry for the dumb question but can you point me to the exact article, can't seem to view it on my phone. Thanks!

**Comment by lambdalisue** [comment]
This repository is for **jupyter notebook** but for **jupyterlab**.
You are asking questions in a wrong place.
