### ISSUE TITLE
MacOS: jupyter-vim-binding support for <C-n>/<C-p> completion

### ISSUE THREAD

**Issue by yelled1** [lambdalisue/jupyter-vim-binding#132]
### Summary
Jupyter-vim-binding supports <C-n>/<C-p> completion does not work
while <C-g> tooltip works well

### Environment

- [ ] Operating system : Mac OSX High Sierra 10.13.6
- [ ] Web browser : Chrome Version 69.0.3497.81 (Official Build) (64-bit)
- [ ] Version or revision of Jupyter Notebook : 4.4.0
- [ ] Revision of jupyter-vim-binding :
jupyter labextension list
JupyterLab v0.34.2
Known labextensions:
   app dir: /home/hoon/.local/share/virtualenvs/simulation-RVBo82bs/share/jupyter/lab
        @jupyterlab/plotly-extension v0.17.1  enabled  OK
        @jupyterlab/shortcutui v0.3.1 disabled OK
        jupyterlab_vim v0.9.0  enabled  OK

### Behavior
<C-p> moves cursor up & <C-n> moves it down within the code cell but not along the completion

#### Expected
<C-p> moves cursor up & <C-n> down along the completion once 
object.<tab> shows the completions

#### Actual
<C-p> moves cursor up & <C-n> moves it down within the code cell

### Step by step procedure
Pls note that 
`jupyter lab --ip=0.0.0.0 --no-browser --port=8888`
is started on the Ubuntu on the Google Cloud
ONLY Chrome browser is run on Mac
http://datasci.brainbuster.com:8888/lab

### What you have done to solve the issue
disabled the shortcut ui

### Remarks
Just likely something to do with Mac OSX. I will see if I can repeat with Ubuntu tonight. Meanwhile, if this is mac specif issue, then pls let me know.  (Esp if the solution is known)

**Comment by lambdalisue** [comment]
If you are using jupyterlab_vim, you should report issue on jupyterlab_vim. Here is for jupyter-vim-binding.

**Comment by yelled1** [comment]
Oops, wrong add-in. My baaad.
