### ISSUE TITLE
Change cell type to markdown?

### ISSUE THREAD

**Issue by bi1yeu** [lambdalisue/jupyter-vim-binding#139]
### Summary

Without jupyter-vim-binding, it's [possible to change a cell type to markdown](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html#Markdown-Cells) by pressing `m` when not in insert mode (when cell has blue outline).

### Environment

- [ ] Operating system : macOS 10.14.2
- [ ] Web browser : Firefox 65.0
- [ ] Version or revision of Jupyter Notebook : 4.4.0
- [ ] Revision of jupyter-vim-binding : v2.1.0

### Behavior

When a cell is highlighted in Jupyter mode (blue outline), press the `m` key

#### Expected

Cell type changes to markdown

#### Actual

Nothing

### What you have done to solve the issue

I couldn't find an issue about exactly this problem. I tried pressing `m` on a cell inside a notebook at https://jupyter.org/try and it worked as expected, changing the cell type to markdown.

**Comment by lambdalisue** [comment]
Use ctrl-2 or cmd-2
https://github.com/lambdalisue/jupyter-vim-binding/blob/master/lib/jupyter/shortcuts.js

**Comment by bi1yeu** [comment]
Ah, I totally missed that list of shortcuts. Thanks, and thanks for the great plugin!
