### ISSUE TITLE
[Feature Request] Swap colon with semi-colon

### ISSUE THREAD

**Issue by sizhky** [lambdalisue/jupyter-vim-binding#147]
Title says it all...
Is there a way to swap colon and semi-colon keys, as I have this habit in general. 

Also in general, I was thinking is there no way to connect system's vim to be used as backed instead of a copy of vim (code-mirror)?

**Comment by lambdalisue** [comment]
I guess it's not possible while CodeMirror's Vim does not have `noremap` feature.

> Also in general, I was thinking is there no way to connect system's vim to be used as backed instead of a copy of vim (code-mirror)?

This plugin does not provide such feature.
