### ISSUE TITLE
Jupyter-vim doesn't connect Vim with Jupyter

### ISSUE THREAD

**Issue by ramm001** [lambdalisue/jupyter-vim-binding#148]
### Summary
Nothing happens

### Environment

- [ ] Operating system : Ubuntu Gnome 18.04 LTS 64bit
- [ ] Web browser : 80.0.3987.106 (Official Build) (64-bit)
- [ ] Version or revision of Jupyter Notebook : 5.7.8
- [ ] Revision of jupyter-vim-binding : 2.0.4
- [ ] vim  8 : yes

### Behavior and all the rest
     After doing everything as appears in the guide https://github.com/wmvanvliet/jupyter-vim, nothing happens. After bringing up the extension and executing "jupyter nbextension enable vim_binding/vim_binding", the code spits out "Enabling notebook extension vim_binding/vim_binding... - Validating: problems found: - require?  X vim_binding/vim_binding". It is told that this problem is harmless, even though I have already downloaded the plugin from github to my computer. I am starting to doubt how harmless that error is.
    Result: Jupyter notebook extensions shows a (!) sign for the vim-binding tab (no access to it anyways, regardless the number of clicks I do).
   After running a qt-console/console and opening vim and type ":JupyterConnect" it spits out that is not a command for Vim.
   Any Suggestions? Is it a problem of mine and/or my installation?

**Comment by lambdalisue** [comment]
You are in the wrong place.
Visit https://github.com/wmvanvliet/jupyter-vim
