### ISSUE TITLE
Vim command mode

### ISSUE THREAD

**Issue by neelpatel09** [lambdalisue/jupyter-vim-binding#15]
How does : mode work in the extension? I'm not able to type any characters there which are mapped to shortcuts (u, i, o, etc.) However, this makes the : code mode really hard to use. Is it possible to disable the shortcuts when in this mode and reenable them when leaving?

To recreate, try to substitute a phrase which contains an i. It will end the command mode and drop back into insert mode.

:%s/test/i

at which point it drops you back in.

**Comment by lambdalisue** [comment]
True. I'll think about it.
