### ISSUE TITLE
not working properly in code cells

### ISSUE THREAD

**Issue by geier** [lambdalisue/jupyter-vim-binding#16]
Hi and thanks for this awesome project. While it works well for me in (large) markdown cells, it doesn't really work in code cells, e.g. I cannot even execute them with `<alt>+<enter>` or `<shift>+<enter>`. Should these vim bindings also work in code cells?

**Comment by lambdalisue** [comment]
Both should work. I recently update the code of jupyter-vim-binding so make sure you are using the latest one and let me know the detail of the issue (version of everything, insert mode or normal mode or command mode or whatever)

**Comment by geier** [comment]
After the update, it works. Thank you very much for this awesome project!
