### ISSUE TITLE
Motion commands (jkhl) perform action once, even when held

### ISSUE THREAD

**Issue by stsievert** [lambdalisue/jupyter-vim-binding#17]
When I press and hold `j` to go down multiple lines, it only goes down one line. I can somewhat get around this with using `20j` to go down 20 lines and [displaying line numbers by default](http://stackoverflow.com/questions/20197471/how-to-display-line-numbers-in-ipython-notebook-code-cell-by-default), but this would be a nice fix.

**Comment by lambdalisue** [comment]
Could not reproduce. I can go down multiple lines with holding `j`. Make sure you are using a latest version and let me know the detail (environment, version, etc.)

Also, try https://codemirror.net/demo/vim.html and if the problem still occur, let them know while the issue may comes from CodeMirror.

**Comment by stsievert** [comment]
Hm this issue still occurs for me on CodeMirror with all major browsers (Safari, Chrome, FF). I'll file an issue with them.

**Comment by lambdalisue** [comment]
Please post a link of an issue here when you make one :-)

**Comment by stsievert** [comment]
GitHub can even do cross-repo autolinks!

**Comment by lambdalisue** [comment]
Yes. Thanks :-)
