### ISSUE TITLE
Notification when the notebook file is saved

### ISSUE THREAD

**Issue by pablocobelli** [lambdalisue/jupyter-vim-binding#18]
This is a great extension, I want to thank you for it as it makes my life a lot easier. 
There's one extra thing that could be useful (as enhancement). Whenever I save the notebook via the interface menu (File -> Save and Checkpoint) I get a notification that the file has been saved (a short message displays next to 'Help' on the menu bar. However, when i do ':w' <enter>, I know it's saved (I see that in the terminal from which I launched the notebook server) but the notebook itself does not display any notification. Could it be possible to add just the same notification that the 'menu bar way' gives?

Thanks.

**Comment by lambdalisue** [comment]
I see, I'll check it.

**Comment by lambdalisue** [comment]
Actually, [it should show a notification](https://github.com/lambdalisue/jupyter-vim-binding/blob/master/vim_binding.js#L51) and mine show notification. Make sure you are using a latest jupyter and jupyter-vim-binding.

**Comment by wilzbach** [comment]
I can confirm that it works fine on my setup too, can you try to patch the notebook save command to see whether it is triggered?

e.g. add this to your `custom.js`

```
require(["notebook/js/notebook"], function(Notebook){
    var save_notebook = Notebook.prototype.save_notebook;
    Notebook.prototype.save_notebook = function(){
        var p = save_notebook.apply(this, arguments);
        p.then(function(){
            console.log('saved');
        }, function(){
            console.error('saving failed');
        });
        return p;
    };
});
```

**Comment by lambdalisue** [comment]
@pablocobelli 

I'm not sure but you may type `:w` in Jupyter's command mode (I sometime does so I wonder)?

You will see a small inputbox (white one if you are using old jupyter-vim-binding, black one if you are using latest) when you hit `:` in Vim's command mode and if you type `w` and `Enter` there, you will see the notification.

![selection_066](https://cloud.githubusercontent.com/assets/546312/11531113/e0cb7afc-993d-11e5-8239-c2b22e6387a0.png)

**Comment by lambdalisue** [comment]
Ping. @pablocobelli  I'll close this issue within several days.
