### ISSUE TITLE
Add better screencast or live demo

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/jupyter-vim-binding#22]
While the current screencast is way old, I would like to add a nice (small size, good quality) screencast on README.md

Or a live demo. Does anybody know the way? I don't want to prepare a server so I would like to know if there is a web service like http://nbviewer.ipython.org/ but for a plugin demo.

**Comment by wilzbach** [comment]
> Or a live demo. Does anybody know the way? I don't want to prepare a server 

Nope, but I know about https://try.jupyter.org/ - maybe we can provide instructions to dynamically load the plugin?

**Comment by wilzbach** [comment]
Hmm I just checked and the git clone fails - it seems that they block http calls to the outside world.

Maybe we can ask the devs nicely

a) to whitelist the url (probably they have blocked all outside connections)
b) to clone this extension too, when they build the Dockerfile

https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile

**Comment by lambdalisue** [comment]
I don't really think they allow (while there are a lot of security risks) but I tried. Thanks for pointing me there :-)

**Comment by lambdalisue** [comment]
This service would help me to create a live demo http://mybinder.org/
