### ISSUE TITLE
indenting issues: delete spaces to previous tab and indentLess

### ISSUE THREAD

**Issue by wilzbach** [lambdalisue/jupyter-vim-binding#29]
I noticed that for some reason CodeMirror only deletes the tabs in individual spaces.
After digging a bit, I found out that the Jupyter devs probably had a similar problem and found a solution, by using the extraKey mapping to this:

``` js
                "Shift-Tab" : "indentLess",
                "Backspace" : "delSpaceToPrevTabStop",
```

An easy fix is to get the CodeMirror configuration from the CodeCell (currently at L367):

``` js
      var cm_config = namespace.CodeCell.options_default.cm_config;
```

However this is probably not so nice for non-code cells.
@lambdalisue do you have an idea how to write a better fix?

Maybe hijacking the different `Cell`s  `.prototype` and defining the default CodeMirror setting in the constructor instead of having one `extraKeys` definition that is the same for all cell types (Jupyter already does, see e.g. [CodeCell](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/codecell.js#L173))?

**Comment by lambdalisue** [comment]
So you would like to do
1. Indent with `Tab`
2. Outdent with `Shift-Tab`
3. Outdent with `Backspace` if there are only spaces before the cursor

Correct?

I will think about this. Let me know I didn't get correctly.

**Comment by wilzbach** [comment]
Yes and as mentioned this is already implemented in Jupyter's `CodeCell` extraKey config, we just overwrite it :(

**Comment by lambdalisue** [comment]
Ok. I find a way.
