### ISSUE TITLE
Autocomplete and '.' mess up.

### ISSUE THREAD

**Issue by TyberiusPrime** [lambdalisue/jupyter-vim-binding#3]
autocompletion (with tab) leads to duplicate content inserted by '.' afterward.

so say you type 'math.fac' and hit tab to complete to 'math.factorial',
then you move down a line and hit '.', you get 'math.facmath.factorial'
instead of math.factorial.

**Comment by lambdalisue** [comment]
I cannot reproduce the behaviour. In my case
1. Type `math.fa`
2. Select `math.factorial` by hitting a down arrow key
3. Hit `Enter` to complete

I'm using Python 3 in Firefox 41.0 in Ubuntu 15 64bit.

>  and hit '.', you get 'math.facmath.factorial'

Why do you hit `.` instead of `Enter`? And hitting `.` lead me to `math.fa.` without completion menu thus this is an expected behaviour for me.

**Comment by TyberiusPrime** [comment]
Sorry if my text was unclear, I hit '.' after the completed auto completion to enter math.factorial again on another line. You know, '.', the magic vim 'do the same thing again' button ;).

If you type math.fac + tab, you autocomplete to the only suggestion, math.factorial, no enter necessary.

**Comment by lambdalisue** [comment]
Now I got it.
1. Type `math.fa`
2. Select `math.factorial` by hitting a down arrow key
3. Hit `Enter` to complete
4. Hit `Enter` to insert a new line
5. Hit `Esc` to leave an insert mode
6. Hit `.` to repeat the previous action

Well, probably there are no hope to fix this. The `.` repeat feature comes from [CodeMirror's Vim mode](http://codemirror.net/doc/manual.html#vimapi), `Tab` completion comes from [Jupyter's completion plugin](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/completer.js). CodeMirror doesn't aware the completion thus it won't be repeated by CodeMirror's `.` repeat feature.

CodeMirror itself has [it's own autocompletion](http://codemirror.net/demo/complete.html) thus if Jupyter would use CodeMirror's autocompletion in the feature, it would be fixed automatically I hope.
