### ISSUE TITLE
Copy to clipboard functionality

### ISSUE THREAD

**Issue by TyberiusPrime** [lambdalisue/jupyter-vim-binding#4]
It would be nice if I could still copy to clipboard instead of just yaking within ipython notebook from the keyboard. Can't seem to find a keybinding for that.

**Comment by lambdalisue** [comment]
It would be nice for me as well but I don't know how.

**Comment by lambdalisue** [comment]
it seems impossible. most browser does not allow to access clipboard because of security reason.

**Comment by TyberiusPrime** [comment]
Yes, but if we manage to release ctrl-c back to it's default browser binding, we should have a regular copy event?

**Comment by lambdalisue** [comment]
Good point. I'll remove the line https://github.com/lambdalisue/jupyter-vim-binding/blob/master/nbextensions/vim_binding.js#L104

**Comment by TyberiusPrime** [comment]
I think something lower down is also hogging the shortcut :(

**Comment by lambdalisue** [comment]
It is a difficult topic. I don't have any compas to select which shortcut is necessary thus I just copied most of that from jupyter's default.

which one do you think "bad mapping"?

**Comment by TyberiusPrime** [comment]
All I know right now is that ctrl-c doesn't work for copy for me even if I remove that line. Ctrl-V in insert mode does work though - even though it works as visual selection in command mode.

**Comment by lambdalisue** [comment]
Hum.... In my case, C-V doesn't work as well. I'll check it

**Comment by lambdalisue** [comment]
Probably we have to end up for enabling system clipboard.
It won't work in [CodeMirror's Vim mode](https://codemirror.net/demo/vim.html). While this plugin rely on CodeMirror's Vim mode, it is not possible to enable the system clipboard.

Although we are vimmer, we have to use a mouse to copy and paste text... **Really inconvenient** :angry:

**Comment by lambdalisue** [comment]
I think I found a compass https://github.com/LightTable/LightTable/issues/688

**Comment by lambdalisue** [comment]
Sigh. https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js#L1265

**Comment by TyberiusPrime** [comment]
I take it that's not just the input mode callback :(

**Comment by lambdalisue** [comment]
Anyway, this is a problem of CodeMirror so I close it.

**Comment by TyberiusPrime** [comment]
Not so fast with the closing, I found a way that works by disabling all ctrl-c binding,
which then has the browser take over:

this.code_mirror.addKeyMap({"Ctrl-C": false});

**Comment by lambdalisue** [comment]
Well. It is good to know but while CodeMirror's default behavior disable `Ctrl-C`, I would like to follow that and that kind of trick should be performed by user.

But anyway, thanks to found the solution. I will add the tips to README.md later

**Comment by lambdalisue** [comment]
https://zenorocha.github.io/clipboard.js/

**Comment by lambdalisue** [comment]
Copy: http://stackoverflow.com/questions/9492842/does-codemirror-provide-cut-copy-and-paste-api
How about paste?

**Comment by lambdalisue** [comment]
https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/

**Comment by lambdalisue** [comment]
Paste with `p` is prob. not possible
http://jsfiddle.net/lambdalisue/bk2kfg4c/1/
