### ISSUE TITLE
Holding motion keys doesn't continue movement

### ISSUE THREAD

**Issue by rawrgulmuffins** [lambdalisue/jupyter-vim-binding#40]
# Expected Behavior

Holding h, j, k, l causes the cursor to continue moving in the direction indicated.
# Current Behavior

Holding h, j, k, l causes the cursor to move once.
# Environment

```
Python3
backports-abc (0.4)
decorator (4.0.6)
Flask (0.10.1)
ipykernel (4.2.1)
ipython (4.0.1)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
itsdangerous (0.24)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.0.3)
jupyter-core (4.0.6)
MarkupSafe (0.23)
mistune (0.7.1)
nbconvert (4.1.0)
nbformat (4.0.1)
notebook (4.0.6)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (7.1.2)
ptyprocess (0.5)
Pygments (2.0.2)
PyYAML (3.11)
pyzmq (15.1.0)
qtconsole (4.1.1)
setuptools (18.2)
simplegeneric (0.8.1)
terminado (0.5)
tornado (4.3)
traitlets (4.0.0)
Werkzeug (0.11.3)
wheel (0.24.0)
```

**Comment by lambdalisue** [comment]
What happen wken you hold hijk in other roftware such as texteditor or notepad?

Which OS do you use?

Which browser do you use?

Do you use a browser plugin such as vimperator, vimnium, or so on? If so, what happen when you disable that.

**Comment by rawrgulmuffins** [comment]
What happen when you hold hijk in other software such as texteditor or notepad?

```
Currently I'm just using the console vim (VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jul  9 2015 23:58:42) installed from homebrew
```

Which OS do you use?

```
OSX Yosemite version 10.10.5
```

Which browser do you use?

```
Chrome version 47.0.2526.106 (64-bit)
```

Do you use a browser plugin such as vimperator, vimnium, or so on? If so, what happen when you disable that.

```
I am not using vimperator, vimnium, or any other key binding plugins. I can disable all of my other plugins (like lastpass, ghostly, adblock, etc.)
```

**Comment by lambdalisue** [comment]
Then what happen when you hold i in your Vim

**Comment by rawrgulmuffins** [comment]
switches to insert mode then

```
iiiiiiiii
```

**Comment by lambdalisue** [comment]
I'm sorry but I cannot reproduce the issue :'(

**Comment by traeki** [comment]
I no longer know where the stackoverflow thread was, but based on some such, I ran

defaults write -g ApplePressAndHoldEnabled -bool false

and restarted my computer.  Works like a charm, now.

Give that a shot, and see if it fixes it.  (I'm using El Capitan, but I don't _think_ that matters for this.)

**Comment by lambdalisue** [comment]
> To type an accented or alternate version of a character, hold a key down until its alternate characters are displayed. 

https://support.apple.com/en-us/HT201586

Aha, that's why. Maybe I should write down _FAQ_ about

``` sh
$ defaults write -g ApplePressAndHoldEnabled -bool false
```

Thing. Thanks @traeki

But wait. He said he could repeat keys in Vim... Hum....

**Comment by rawrgulmuffins** [comment]
I'll test this when I'm home tonight and have access to my laptop.

**Comment by lambdalisue** [comment]
ping @rawrgulmuffins How's thing going?
