### ISSUE TITLE
Re-enable Ctrl-j/k movement in Normal mode

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/jupyter-vim-binding#41]
Probably I should clear all shortcuts in Edit mode and restore in Normal mode.

**Comment by ElDeveloper** [comment]
Just started using this extension (:beer: great work) and noticed that this would still be useful. My main discontents with the jupyter notebook shortcuts were restricted to text editing, aside from that I think the shortcuts for "normal mode" work great.

**Comment by lambdalisue** [comment]
Now you can move around with hitting `j/k` only. Thanks to https://github.com/lambdalisue/jupyter-vim-binding/pull/31

**Comment by ElDeveloper** [comment]
Awesome, cheers!
