### ISSUE TITLE
Staying in insert mode after running cell

### ISSUE THREAD

**Issue by igorpejic** [lambdalisue/jupyter-vim-binding#42]
What I would want:
1. Typing something in insert mode
2. Ctrl+Enter
3. The code runs and returns me into insert mode where I left off

Is there a customization for this? Thanks

**Comment by lambdalisue** [comment]
Currently no. But I think what you said makes sense so I would like to change the default behaviour.

To make that, needs
- [ ] Create new actions like `vim_binding:run-cell-and-edit` or so on which enter edit mode after [`jupyter:run-cell`](https://github.com/lambdalisue/jupyter-vim-binding/blob/master/vim_binding.js#L270-L273) or so on like [`vim_binding:change-cell-to-raw-and-edit`](https://github.com/lambdalisue/jupyter-vim-binding/blob/master/vim_binding.js#L253-L259)
- [ ] Replace default bindings

For now, I don't really have time to implement the above so give me time or send me a PR ;-)
