### ISSUE TITLE
Support multi-cell editing in Jupyter notebook 4.1

### ISSUE THREAD

**Issue by jhrmnn** [lambdalisue/jupyter-vim-binding#44]
Jupyter notebook [introduced](https://blog.jupyter.org/2016/01/08/notebook-4-1-release/) multi-cell editing in 4.1, which introduced a new shortcut for extending the cell selection.

**Comment by lambdalisue** [comment]
May I ask what kind of shortcuts did they add?

**Comment by jhrmnn** [comment]
With <kbd>SHIFT</kbd>+<kbd>down</kbd>/<kbd>J</kbd> or <kbd>SHIFT</kbd>+<kbd>up</kbd>/<kbd>K</kbd>, you extend the current selection down or up, respectively.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/jupyter-vim-binding/blob/master/vim_binding.js#L420-L421
https://github.com/lambdalisue/jupyter-vim-binding/blob/master/vim_binding.js#L320-L321

Already implemented I think.

**Comment by jhrmnn** [comment]
Yeah. Looks like it was implemented the same day I submitted this issue.
