### ISSUE TITLE
`s` in visual-block mode doesn't behave like in vim

### ISSUE THREAD

**Issue by pseyfert** [lambdalisue/jupyter-vim-binding#50]
marking text in a cell in visual block mode with ctrl+v does allow to delete the text with `d` and one can insert text at the beginning of the marked section with shift+i, but in vim also `s` works with visual block mode - it deletes the marked part and switches to insert mode to insert text in all marked lines. For me, jupyter-vim-bindings only enter the text in the first marked line.

A small demonstration here: http://virgilio.mib.infn.it/~seyfert/videos/visual-block-s.webm

what I do there is in both cases:
- switch to visual-block mode with ctrl+v
- mark the "wr" part
- hit `s`
- type "td[esc]j"

I'm using fbb5b670e73252406e2cd10b75819f9b4cd85eec

**Comment by lambdalisue** [comment]
Did you try https://codemirror.net/demo/vim.html ? If the behavior could be reproduced in that, it is an issue of CodeMirror and could not be fixed in this plugin.

**Comment by pseyfert** [comment]
Thanks for the pointer,
CodeMirror fails visual-block `s` as well.

**Comment by lambdalisue** [comment]
Then it cannot be fixed within this plugin sorry. CodeMirror is wonderful but not perfect. There are a lot of features which cannot be used in CodeMirror...

**Comment by pseyfert** [comment]
This is now reported as fixed in codemirror/CodeMirror#3868
