### ISSUE TITLE
How to run a cell and do nothing else?

### ISSUE THREAD

**Issue by traeki** [lambdalisue/jupyter-vim-binding#59]
### Summary

I'm sure I'm missing something obvious here.  How can I currently run the cell I'm in without moving to the next cell, creating a cell, etc?  Ideally I would run a cell and end in Jupyter mode (so that Markdown renders), but I'd settle for just a shortcut that runs the cell I'm in without other effects.

**Comment by lambdalisue** [comment]
`Ctrl-Enter`. But it return into _Normal mode_ so Markdown is not rendered.

**Comment by traeki** [comment]
Ahah, or for OS X, which I failed to specify, command-enter.

Okay, thanks, closing this.
