### ISSUE TITLE
Help me file??

### ISSUE THREAD

**Issue by robbyki** [lambdalisue/jupyter-vim-binding#6]
Hi,
Thanks for this. Really want to try it out and followed installation steps but cannot follow the video. Is there any kind of help doc  I could follow instead for how to use? Can't figure out what the key commands are. thank you.

**Comment by lambdalisue** [comment]
First of all, this plugin does not provide any command.
If you install this plugin, the Vim-mode of CodeMirror should be automatically turned on.

What is written in console (browser console, not jupyter console) when you execute the below

```
%%javascript
Jupyter.utils.load_extensions('vim_binding')
```

**Comment by robbyki** [comment]
Do you mean IPython Terminal when you say "browser console? When I try it in IPython 4.0 I get:

``` javascript
In [1]: %%javascript                                                                                                               
   ...: Jupyter.utils.load_extensions('vim_binding')                                                                               
   ...:                                                                                                                            
<IPython.core.display.Javascript object> 
```

**Comment by robbyki** [comment]
Disregard. Needed to restart jupyter. Thanks a lot for this.

**Comment by lambdalisue** [comment]
I see. I ment console of developer tools while errors may be written in there because it is javascript.
