### ISSUE TITLE
Insert cell above?

### ISSUE THREAD

**Issue by rsdenijs** [lambdalisue/jupyter-vim-binding#66]
In the documentation we have both Ctrl-O and O to instert a cell bellow from Jupyter mode...
... is this intentional?
... how would you insert a cell above?

**Comment by lambdalisue** [comment]
Oops.

https://github.com/lambdalisue/jupyter-vim-binding/blob/master/lib/jupyter/shortcuts.js#L56-L57

You are right. This is like a typo. Thanks ;-)

**Comment by rsdenijs** [comment]
But is it intentional that we are not able to insert/delete a cell  without pressing S-Esc before? Seems weird because this is a very frequent thing to do in jupyter

**Comment by lambdalisue** [comment]
C-o,o or C-o,O does what you want in command mode :-]

Several frequent features have C-o prefix mapping in command mode like C-o mapping in insert mode of a native Vim.

Does it help?

**Comment by rsdenijs** [comment]
Ahh yes that works! This is what i was looking for. 

I do think that going from typing something and doing

> Esc,  mb    

to

> Esc, C-o, S-o

for cell creation is a bit of a drag. Would it make sense to be able to do these Jupyter commands directly from insert mode so we just could do C-o, S-o? Or does this create conflicts?

**Comment by lambdalisue** [comment]
> Would it make sense to be able to do these Jupyter commands directly from insert mode so we just could do C-o, S-o? Or does this create conflicts?

I think it is worth considering but in my opinion:
- _Insert_ mode should focus to inserting characters but editing contents. A native Vim does not have mappings in _Insert_ mode except `C-o` (onetime escape), `C-n/p` (completion), or whatever which are closely related to inserting characters, indicating that editing contents should be performed in _Command (Normal)_  mode or with `C-o` prefix
- A native Vim behave `Insert -> Normal -> Insert` with `C-o` but if I accept `C-o` in jupyter-vim-binding as your suggestion, it would become `Command (Normal) -> Jupyter -> Command` so it will conflict psychologically with one in a native Vim (not physically while `C-o` of CodeMirror in _Insert_ mode does not work) 
- Vimmers prefer to stay in _Normal_ mode (_Command_ mode in jupyter-vim-binding) so I don't really think I need to expose many features in _Insert_ mode

But again, I think it is worth considering so if you are not convinced with my answer, create a new issue for discussion. I'm welcome to discuss features ;-)

**Comment by rsdenijs** [comment]
I am currently using the plugin full-time so I should be able to give some experience-based feedback soon.
