### ISSUE TITLE
Cmd-C maps to 'interrupt kernel' when focused outside of cell on Mac

### ISSUE THREAD

**Issue by yichuan1118** [lambdalisue/jupyter-vim-binding#70]
### Summary

Cmd-C maps to copy when cursor is focused inside an cell to edit code.
However Cmd-C maps to 'interrupt kernel' when focused outside of cell on Mac, e.g. when you select some text of the cell run output.
### Environment
- [ ] Operating system : Mac 10.11
- [ ] Web browser : Chrome 50.0.2661.86
- [ ] Version or revision of Jupyter Notebook : 4.2.0-0949a69
- [ ] Revision of jupyter-vim-binding : (e.g. 5a057d6)
#### Expected

Cmd-C maps to copy 
#### Actual

 Cmd-C maps to 'interrupt kernel' when focused outside of cell on Mac, e.g. when you select some text of the cell run output.

**Comment by lambdalisue** [comment]
Hum... Make sense thanks. I'll change the default mapping.

For instance, you can use [keyboard-shortcut-editor](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/keyboard_shortcut_editor) plugin to change the mapping in case you haven't noticed that ;-)

**Comment by yichuan1118** [comment]
Awesome, thanks!

**Comment by lambdalisue** [comment]
Implemented in develop branch ;-)

**Comment by yichuan1118** [comment]
Awesome! Thanks!
