### ISSUE TITLE
jk -> Esc does not mix well with "." (repeat last command)

### ISSUE THREAD

**Issue by ghost** [lambdalisue/jupyter-vim-binding#72]
### Environment

Ubuntu
Google Chrome
Current version

I have the following binding in my custom.js:

```
CodeMirror.Vim.map("jk", "<Esc>", "insert");
```

The behavior works correctly for mapping "jk" -> Esc. However, the behavior of "." (i.e. repeat last command) for a command that ended by using "jk" in place of Esc is incorrect. It has the effect of inserting an extra j after each command. For example, in a new notebook, the sequence of keystrokes.

iajk.

Will produce:

aja

Rather than:

aa

This causes problems for anyone who uses both jk -> Esc or jj -> Esc and also uses the "." (repeat last command).

**Comment by lambdalisue** [comment]
Hum... It seems a limitation of CodeMirror's Vim mode.
You probably need to make an issue on CodeMirror's repository.

**Comment by ghost** [comment]
Okay, thanks for looking into it! Don't think I care enough to bother further but yea, it doesn't really work.
