### ISSUE TITLE
Not able to copy from output cells with keyboard shortcut

### ISSUE THREAD

**Issue by rsdenijs** [lambdalisue/jupyter-vim-binding#77]
It seems it is not possible to copy from the _cell output_ with Ctrl-C. The same action does work on input cells. The only thing that works is right-click and copy. I am on Chrome.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/jupyter-vim-binding/issues/70

I'm sorry I haven't fix this yet.

**Comment by rsdenijs** [comment]
I missed that one. Thanks!
