### ISSUE TITLE
long press HJKL to move continues not working.

### ISSUE THREAD

**Issue by kernel8liang** [lambdalisue/jupyter-vim-binding#81]
when I long press HJKL I want to continues moving forward, but it dose not.

OS :  OS X 10.11.6 
jupyter: 4.1.0
chrome:  51.0.2704.103 (64-bit)

**Comment by lambdalisue** [comment]
I'm sorry but I dom't get the situation, Could you provide me how I can reproduce and your expectation a litte bit more?

**Comment by kernel8liang** [comment]
I installed this plugin without any extra config, just a fresh install, and I get this issue.
I will try around, if I get some clue I will post it here.

**Comment by lambdalisue** [comment]
Hum... So are these help?

https://github.com/lambdalisue/jupyter-vim-binding/issues/40
https://github.com/lambdalisue/jupyter-vim-binding/issues/17

**Comment by pingzh** [comment]
This is helpful: https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-auto-repeat-keys-on-osx

After I ran the command, I also restarted my chrome and it works great!
