### ISSUE TITLE
Completion bindings

### ISSUE THREAD

**Issue by clearissimple** [lambdalisue/jupyter-vim-binding#82]
As of Firefox 48 certain mappings are no longer available to client side javascript (as in Crome). These are `Ctrl-n`, `Ctrl-t` and `Ctrl-w`. The README.md should be probably updated.

Changing the code in `lib/jupyter/completer.js` to check for `Ctrl-m` instead of `Ctrl-n` worked out fine. Even though I mapped it to something different in Jupyter command and edit modes, the down action during completion takes precedence.

**Comment by lambdalisue** [comment]
Oh... no.... How could we survive... Thanks anyway for letting me know that.

**Comment by lambdalisue** [comment]
It seems using [Opera](http://www.opera.com) is a current best solution while it can disable all keyboard shortcuts manually like below.

![selection_031](https://cloud.githubusercontent.com/assets/546312/17918196/e30f8506-69fd-11e6-80fb-e0ed80f91a76.png)

**Comment by clearissimple** [comment]
https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/

This addon allows to disable these shortcuts for Firefox and they become available to JavaScript.

**Comment by lambdalisue** [comment]
Cool thanks!
