### ISSUE TITLE
When activating Vim bindings, my keyboard shortcut editor disappears

### ISSUE THREAD

**Issue by tknuth** [lambdalisue/jupyter-vim-binding#84]
### Summary

Vim bindings seem to disable the dropdown menus in the keyboard shortcuts. It looks as custom shortcuts extension were not activated.
### Environment
- [ ] Operating system : OS X 10.10.5
- [ ] Web browser : Chrome 52.0.2743.116 (64-bit)
- [ ] Version or revision of Jupyter Notebook : 4.2.2
- [ ] Revision of jupyter-vim-binding : Where do I find that?
### Behavior

No keyboard editor.
#### Expected

There should be one.
#### Actual

See above.
### Step by step procedure
1. Start local Jupyter Notebook by `jupyter notebook`
2. Access http://localhost:8888/
3. Click on help, keyboard shortcuts
### What you have done to solve the issue

Tried activating/deactivating in different orders, reinstalled. Did not help.
### Remarks

Awesome software nevertheless!

**Comment by lambdalisue** [comment]
Related to #83 
It is a kind bug and I'll check if there is any workaround in this weekend probably ;-)

**Comment by tknuth** [comment]
Thank you for sharing your software with us! :-)

**Comment by tknuth** [comment]
Is there any progress on this or any way to help you?

**Comment by lambdalisue** [comment]
Oops. Sorry. Well the priority of the development of this plugin is a bit lower for now (I would like to spent time to write other Vim plugins.) So any kind of helps (investigation, PR, etc.) are welcome :+1:

**Comment by lambdalisue** [comment]
It seems the latest jupyter-vim-binding with the latest jupyter fix the issue. Right?

**Comment by DrJimFan** [comment]
Yes, I can confirm that the latest Jupyter 5.0 solves the problem.

**Comment by lambdalisue** [comment]
Cool thanks
