### ISSUE TITLE
Yank (Y) doesn't work as expected

### ISSUE THREAD

**Issue by buzypi** [lambdalisue/jupyter-vim-binding#88]
### Summary
When you yank a link in Vim using Y and press p, it pastes the entire line that the cursor is currently in the next line and positions the cursor in the newly created line.

### Step by step procedure

1. Insert a cell
2. Click in the cell
3. Press i
4. Type a sentence like "The quick brown fox jumps over the lazy dog"
5. Press Escape
6. Press Y
7. Press p

## Actual
A part of the line gets copied in between the existing line.

### Expected
The entire line should get copied in the next line and the cursor must be positioned in the new line.

### Remarks

Thanks for the binding. :)

**Comment by lambdalisue** [comment]
Use `yy` instead of `Y` or remap `Y` to `yy` while
- A native `Y` should do `y$` (like `C`, `D`) but actually do `yy`. It may because of some historical reason. [ref](http://stackoverflow.com/questions/3517057/why-does-y-do-the-same-thing-as-yy)
- CodeMirror itself map `Y` to `y$` ([ref](https://codemirror.net/demo/vim.html)) and I would like to follow the CodeMirror's default in this (`Y`) case while the native `Y` really doesn't make sense to me.

**Comment by lambdalisue** [comment]
Please close the PR if you are satisfied with my answer or give me a good reason to follow the native Vim's mapping :+1: .

**Comment by buzypi** [comment]
That sounds reasonable. I didn't know yy works.

**Comment by dsummersl** [comment]
Personally I've found the non-standard behavior of CodeMirror to vim/vi behavior of Y quite interrupts my workflow. Anyone have a snippet they could share to change this setting for jupyter (completely understand not wanting to deviate from CodeMirror's mappings)?

**Comment by dsummersl** [comment]
Here it is for posterity:

```
// Configure CodeMirror
require([
  'nbextensions/vim_binding/vim_binding',   // depends your installation
], function() {
  // Map Y to yy
  CodeMirror.Vim.map("Y", "yy", "normal");
});
```

(And restart your notebook, which I forgot to do. woops! 😸 )

**Comment by lambdalisue** [comment]
Please feel free to edit https://github.com/lambdalisue/jupyter-vim-binding/wiki/Customization 👍

**Comment by dsummersl** [comment]
done, thanks!
