### ISSUE TITLE
Navigating tab-completions

### ISSUE THREAD

**Issue by haakenlid** [lambdalisue/jupyter-vim-binding#9]
This was also mentioned in the vimrecption repo. https://github.com/ivanov/ipython-vimception/issues/9
Ctrl+P and Ctrl+N would be nice, but at least it would be nice to go to the next completion every time you press tab. It seems that the only way to navigate multiple tab completions is to use the arrow keys, which is super annoying.

**Comment by lambdalisue** [comment]
while jupyter use it's own completion code and navigation keys are hard written, it's not possible to change it...

**Comment by lambdalisue** [comment]
@haakenlid I said it is too difficult to implement but in #51, I success. In case if you are still interested in about this feature ;-)
