### ISSUE TITLE
how to turn off blinking cursor in code cell

### ISSUE THREAD

**Issue by jgors** [lambdalisue/jupyter-vim-binding#90]
I see here [1] that there is a `cursorBlinkRate` parameter that can be set to `0` to turn off cursor blinking in the cells, though can't figure out how this should be implemented in the custom.js file.  It seems like it should be pretty straightforward, though haven't been able to figure out how to do so.

Thanks in advance

[1] http://codemirror.net/doc/manual.html#config

**Comment by jgors** [comment]
Ok, figured it out, though am not sure this is the best/right way to do it, but by putting this in the custom.js file it works:

```
IPython.Cell.options_default.cm_config.cursorBlinkRate=0;
```

**Comment by chenchr** [comment]
@jgors  Hello. Could you tell me where the ```custom.js```  is ?
