### ISSUE TITLE
Problem with vim commands (using :)

### ISSUE THREAD

**Issue by mesalas** [lambdalisue/jupyter-vim-binding#94]
### Summary
I cant get any vim commands to work. eg:
when I enter `:/whatiwanttofind)`
I get `Not an editor command ":/whatiwanttofind`
Similar behavior is seen for all commands I have tried. 
Otherwise the keybindings work fine eg: hjkl (for left down up right) and so on 

### Environment

- [ ] OS: macOS Sierra 10.12.3 
- [ ] Browser : Firefox 52.0.1 (64-bit)
- [ ] Jupyter version : 4.4.1
- [ ] Revision of jupyter-vim-binding : 91de1d8

**Comment by lambdalisue** [comment]
commands are not defined except for saving

**Comment by mesalas** [comment]
Thanks for the quick reply.

> commands are not defined except for saving

Fair enough, that explains it 😄 I have somehow missed that.
is it possible to define them?

**Comment by lambdalisue** [comment]
Prob. yes. https://codemirror.net/doc/manual.html#vimapi said defineEx can define ex command but I have not tried so not sure.

**Comment by mesalas** [comment]
Ok after looking through [https://codemirror.net/keymap/vim.js](https://codemirror.net/keymap/vim.js) I now realize what i'm doing wrong.
Lots of the commands are in fact implemented, I just do not need the initial `:`. Eg if I want to search i just press `/` and not `:/`

this kinda fixed my problem. Thanks a bunch
