### ISSUE TITLE
Mapping keys, configuration.

### ISSUE THREAD

**Issue by gusseppe** [lambdalisue/jupyter-vim-binding#96]
### Summary
To sum up, I want to map the h,j,k,l keys to j,k,l,; 
In other words I would like to put my fingers (right hand) one step right.

### Environment

- [Ubuntu Gnome 14.04 64bit ] Operating system : (e.g. Ubuntu Gnome 15.04 64bit)
- [ Chrome 57.0.2987.98 (64-bit)] Web browser : (e.g. Firefox 44.0.2)
- [ 5.0] Version or revision of Jupyter Notebook : (e.g. 4.1 or 620fb29)
- [Last ] Revision of jupyter-vim-binding : (e.g. 

### Step by step procedure

require([
  'nbextensions/vim_binding/vim_binding',   // depends your installation
], function() {

  CodeMirror.Vim.map("l", "<Plug>(vim-binding-gk)", "normal");
  CodeMirror.Vim.map("k", "<Plug>(vim-binding-gj)", "normal");
  CodeMirror.Vim.map("gk", "<Plug>(vim-binding-l)", "normal");
  CodeMirror.Vim.map("gj", "<Plug>(vim-binding-k)", "normal");
  
});

I've mapped successfully the k,l,; keys, but mapping the h into j was not possible so far.

**Comment by lambdalisue** [comment]
Currently, it's not possible I think while CodeMirror does not have noremap alternative.
This is an issue of CodeMirror
