### ISSUE TITLE
Does this can run in windows?

### ISSUE THREAD

**Issue by spk921** [lambdalisue/jupyter-vim-binding#98]
### Summary
Is this runnable in window10 platform? 

Enabling notebook extension vim_binding/vim_binding...
      - Validating: problems found:
        - require?  X vim_binding/vim_binding

I have above problem. 
Thank you

### Environment

- [Windows10 ] Operating system : (e.g. Ubuntu Gnome 15.04 64bit)
- [Explore ] Web browser : (e.g. Firefox 44.0.2)
- [ ] Version or revision of Jupyter Notebook : (e.g. 4.1 or 620fb29)
- [ ] Revision of jupyter-vim-binding : (e.g. 5a057d6)

### Step by step procedure

1. Start local Jupyter Notebook by `jupyter notebook`
2. Access http://localhost:8888/
3. etc.

### What you have done to solve the issue

For example, the behavior is confirmed with Firefox 44.0.2 and Google Chrome xx.xx.xx and could not be reproduced in Firefox but Chrome or what ever.

### Remarks

If any

**Comment by lambdalisue** [comment]
See https://github.com/lambdalisue/jupyter-vim-binding/issues/86

**Comment by hongsoog** [comment]
Yes it runs on Windows 10.

1. install git if you don't have.
Open Anaconda Prompt, and run "conda install git"

2. cd to your nbextensions folders (ex. C:/user/yourname/Anaconda3/share/jupyter/nbextensions)
 and run "git clone https://github.com/lambdalisue/jupyter-vim-binding vim_binding"

3. Check "VIM binding" in Nbextensions tab whin Jupyter Notebook in browser.
